version: '3'
services:
  mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: meryemar
        MONGO_INITDB_ROOT_PASSWORD: 123456
        MONGO_INITDB_DATABASE: routing 
      volumes:         
        - ./mongodb_server_data:/data/db         
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        
      
  routing-service:    
    container_name: routing-service    
    build:      
      context: ./
    ports: 
        - "3002:3003"

          